// <auto-generated />
using CaMan.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaMan.Persistance.Migrations
{
    [DbContext(typeof(CaManDbContext))]
    [Migration("20240809121822_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CaMan.Domain.Campaigns.Campaign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("CaMan.Domain.Campaigns.CampaignContact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignContact");
                });

            modelBuilder.Entity("CaMan.Domain.Contacts.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AdministrativeRegionId")
                        .HasColumnType("BLOB");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommunicationMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MunicipalUnitId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("MunicipalityId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RegionalUnitId")
                        .HasColumnType("BLOB");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeRegionId");

                    b.HasIndex("MunicipalUnitId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("RegionalUnitId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("CaMan.Domain.ElectoralBodies.AdministrativeRegion", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdministrativeRegion");
                });

            modelBuilder.Entity("CaMan.Domain.ElectoralBodies.MunicipalUnit", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MunicipalUnit");
                });

            modelBuilder.Entity("CaMan.Domain.ElectoralBodies.Municipality", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("CaMan.Domain.ElectoralBodies.RegionalUnit", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegionalUnit");
                });

            modelBuilder.Entity("CaMan.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CaMan.Domain.Campaigns.CampaignContact", b =>
                {
                    b.HasOne("CaMan.Domain.Campaigns.Campaign", null)
                        .WithMany("CampaignContacts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaMan.Domain.Contacts.Contact", b =>
                {
                    b.HasOne("CaMan.Domain.ElectoralBodies.AdministrativeRegion", "AdministrativeRegion")
                        .WithMany()
                        .HasForeignKey("AdministrativeRegionId");

                    b.HasOne("CaMan.Domain.ElectoralBodies.MunicipalUnit", "MunicipalUnit")
                        .WithMany()
                        .HasForeignKey("MunicipalUnitId");

                    b.HasOne("CaMan.Domain.ElectoralBodies.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId");

                    b.HasOne("CaMan.Domain.ElectoralBodies.RegionalUnit", "RegionalUnit")
                        .WithMany()
                        .HasForeignKey("RegionalUnitId");

                    b.OwnsOne("CaMan.Domain.Shared.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<string>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RegionalPrefix")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contact");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("AdministrativeRegion");

                    b.Navigation("MunicipalUnit");

                    b.Navigation("Municipality");

                    b.Navigation("PhoneNumber");

                    b.Navigation("RegionalUnit");
                });

            modelBuilder.Entity("CaMan.Domain.Users.User", b =>
                {
                    b.HasOne("CaMan.Domain.Contacts.Contact", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("ContactInfoId");

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("CaMan.Domain.Campaigns.Campaign", b =>
                {
                    b.Navigation("CampaignContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
