name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests and Collect Code Coverage
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Report Generator
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator "-reports:./**/coverage.cobertura.xml" "-targetdir:coverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

      - name: Publish Code Coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: "**/coverage.cobertura.xml"
